### ISSUE TITLE
MQTT reconnecting all the time on testnet v3

### ISSUE THREAD

**Issue by lumir-mrkva** [maticnetwork/dagger.js#29]
I'm getting `reconnecting...` message every minute or so in the log. From code I can see this is caused by `mqtt` reconnecting.

I am using `https://testnetv3-dagger.matic.network` dagger server.

Is this behaviour expected? 

Anyway I would prefer to replace `console.log` with a listener, so I can choose how to react in that scenario.

**Comment by itzmeanjan** [comment]
Please don't use `testnetv3`, it's deprecated. Only [these](https://docs.matic.network/docs/develop/dagger#network) networks are supported by dagger, as of now.
